spring.datasource.url=jdbc:mysql://localhost:3306/vod?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true
info.app.name=Guild Bank VOD
info.app.description=Demo bank gildii z integracj\u0105 GW2 API
info.app.author=TwojeImie